In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import AP1 as ap

In [7]:
u_c = np.array( [ 8, 7, 5.9, 5, 4.4, 4, 3.1, 3, 2.2, 2, 1.5, 1, 0.6, 0.3, 0.1]) * 5
t_c = np.array( [ 0, 0.4, 1, 1.6, 2, 2.3, 3, 3.1, 4, 4.3, 5, 6, 7, 8, 8.8]) * 2 

u_r = np.array( [ 8, 7, 6.2, 6.0, 5, 4.8, 4, 3.7, 3, 2.4, 2, 1.8, 1.5, 1.3, 1.0, 0.8]) *5
t_r = np.array( [ 0, 0.6, 1, 1.2, 1.8, 2, 2.8, 3, 4, 5, 5.7, 6, 7, 8, 9, 10]) *2 

du_c = np.sqrt((u_c * 0.03)**2 + (0.5)**2)
du_r = np.sqrt((u_r * 0.03)**2 + (0.5)**2)

dt_c = np.sqrt((t_c * 0.03)**2 + (0.2)**2)
dt_r = np.sqrt((t_r * 0.03)**2 + (0.2)**2)


data = pd.DataFrame(data=[u_c, du_c, t_c, dt_c, u_r, du_r, t_r, dt_r],index=['U_c','dU_c','t_c','dt_c', 'u_r','du_r','t_r','dt_r']).T

In [5]:
data

     U_c      dU_c   t_c          dt_c   u_r      du_r   t_r          dt_r
0   40.0  1.300000   0.0  2.000000e-07  40.0  1.300000   0.0  2.000000e-07
1   35.0  1.162970   0.8  2.400000e-02  35.0  1.162970   1.2  3.600000e-02
2   29.5  1.016477   2.0  6.000000e-02  31.0  1.055888   2.0  6.000000e-02
3   25.0  0.901388   3.2  9.600000e-02  30.0  1.029563   2.4  7.200000e-02
4   22.0  0.828010   4.0  1.200000e-01  25.0  0.901388   3.6  1.080000e-01
5   20.0  0.781025   4.6  1.380000e-01  24.0  0.876584   4.0  1.200000e-01
6   15.5  0.682807   6.0  1.800000e-01  20.0  0.781025   5.6  1.680000e-01
7   15.0  0.672681   6.2  1.860000e-01  18.5  0.747011   6.0  1.800000e-01
8   11.0  0.599083   8.0  2.400000e-01  15.0  0.672681   8.0  2.400000e-01
9   10.0  0.583095   8.6  2.580000e-01  12.0  0.616117  10.0  3.000000e-01
10   7.5  0.548293  10.0  3.000000e-01  10.0  0.583095  11.4  3.420000e-01
11   5.0  0.522015  12.0  3.600000e-01   9.0  0.568243  12.0  3.600000e-01
12   3.0  0.508035  14.0  4.200000e-01   7.5  0.548293  14.0  4.200000e-01
13   1.5  0.502021  16.0  4.800000e-01   6.5  0.536680  16.0  4.800000e-01
14   0.5  0.500225  17.6  5.280000e-01   5.0  0.522015  18.0  5.400000e-01
15   NaN       NaN   NaN           NaN   4.0  0.514198  20.0  6.000000e-01

In [9]:

print(data.to_latex(index=False))

\begin{tabular}{rrrrrrrr}
\toprule
  U\_c &      dU\_c &   t\_c &      dt\_c &   u\_r &      du\_r &   t\_r &      dt\_r \\
\midrule
 40.0 &  1.300000 &   0.0 &  0.200000 &  40.0 &  1.300000 &   0.0 &  0.200000 \\
 35.0 &  1.162970 &   0.8 &  0.201435 &  35.0 &  1.162970 &   1.2 &  0.203214 \\
 29.5 &  1.016477 &   2.0 &  0.208806 &  31.0 &  1.055888 &   2.0 &  0.208806 \\
 25.0 &  0.901388 &   3.2 &  0.221847 &  30.0 &  1.029563 &   2.4 &  0.212565 \\
 22.0 &  0.828010 &   4.0 &  0.233238 &  25.0 &  0.901388 &   3.6 &  0.227297 \\
 20.0 &  0.781025 &   4.6 &  0.242990 &  24.0 &  0.876584 &   4.0 &  0.233238 \\
 15.5 &  0.682807 &   6.0 &  0.269072 &  20.0 &  0.781025 &   5.6 &  0.261197 \\
 15.0 &  0.672681 &   6.2 &  0.273123 &  18.5 &  0.747011 &   6.0 &  0.269072 \\
 11.0 &  0.599083 &   8.0 &  0.312410 &  15.0 &  0.672681 &   8.0 &  0.312410 \\
 10.0 &  0.583095 &   8.6 &  0.326441 &  12.0 &  0.616117 &  10.0 &  0.360555 \\
  7.5 &  0.548293 &  10.0 &  0.360555 &  10.0 &  0.583095 &  11.4 &  0.396187 \\
  5.0 &  0.522015 &  12.0 &  0.411825 &   9.0 &  0.568243 &  12.0 &  0.411825 \\
  3.0 &  0.508035 &  14.0 &  0.465188 &   7.5 &  0.548293 &  14.0 &  0.465188 \\
  1.5 &  0.502021 &  16.0 &  0.520000 &   6.5 &  0.536680 &  16.0 &  0.520000 \\
  0.5 &  0.500225 &  17.6 &  0.564610 &   5.0 &  0.522015 &  18.0 &  0.575847 \\
  NaN &       NaN &   NaN &       NaN &   4.0 &  0.514198 &  20.0 &  0.632456 \\
\bottomrule
\end{tabular}